module.exports = [
  "Alert component",
  "This modal component has a fixed width of 280px.",
  "This time we stack the buttons to give the labels plenty of room.",
  "Good luck",
  "about",
  "accessibility",
  "account",
  "back to top",
  "Cancel",
  "careers",
  "chat",
  "contact",
  "contact us",
  "customers",
  "education",
  "english",
  "features",
  "guidelines",
  "help",
  "home",
  "In a horizontal grid",
  "investors",
  "jobs",
  "learn more",
  "log in",
  "media kit",
  "more",
  "new & noteworthy",
  "play video",
  "point of Sale",
  "privacy policy",
  "privacy and security",
  "products",
  "resources",
  "Save document",
  "search",
  "shop now",
  "sign in",
  "sign up",
  "skip to main content",
  "stories",
  "support",
  "terms",
  "terms of service",
  "timeline",
  "toggle navigation",
  "Two cards"
];