module.exports = [
  "about",
  "accessibility",
  "account",
  "back to top",
  "careers",
  "chat",
  "contact",
  "contact us",
  "customers",
  "education",
  "english",
  "features",
  "guidelines",
  "help",
  "home",
  "investors",
  "jobs",
  "learn more",
  "log in",
  "media kit",
  "more",
  "new & noteworthy",
  "play video",
  "point of Sale",
  "privacy policy",
  "privacy and security",
  "products",
  "resources",
  "search",
  "shop now",
  "sign in",
  "sign up",
  "skip to main content",
  "stories",
  "support",
  "terms",
  "terms of service",
  "timeline",
  "toggle navigation",
];